In [4]:
n=int(input())
b,c=[],[]
a=list(map(int,input("Enter the numbers:").split()))
for i in a:
    b.append(str(i))
#print(b)
for i in range(len(b)):
    c.append(int(b[i][len(b[i])//2]))
print(sum(c))

4
Enter the numbers:34756 84568 45658 56494
22


## DATA ANALYSIS
**meaningful information said to be DATA

## importing Modules
- Numpy
- pandas

## Numpy is Numerical Python
- deal with array type of data,Scientific Computation

In [5]:
import numpy as np

In [6]:
np.__version__

'1.20.1'

In [7]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

# array creation()
- array() is the submodule in python
- np.array(iterable)

In [9]:
print(np.array([2,3,3,44,332,434]))

[  2   3   3  44 332 434]


In [10]:
# tuple into array
print(np.array((34,53,453,53,65)))

[ 34  53 453  53  65]


In [11]:
print(np.array([2,3,3,44,332,434],dtype="str"))

['2' '3' '3' '44' '332' '434']


In [12]:
print(np.array(range(10,20)))

[10 11 12 13 14 15 16 17 18 19]


In [13]:
print(np.array(range(10,20,2)))

[10 12 14 16 18]


In [15]:
print(np.array(range(50,20,-5)))

[50 45 40 35 30 25]


## Multidimensional Arrays

In [20]:
print(np.array([[52,25,35,3,5,6],[66,46,3,6,36,3]]))

[[52 25 35  3  5  6]
 [66 46  3  6 36  3]]


In [21]:
li=np.array([[52,25,35,3,5,6],[66,46,3,6,36,3]])
print(li)

[[52 25 35  3  5  6]
 [66 46  3  6 36  3]]


In [22]:
li.dtype

dtype('int32')

In [23]:
li.size

12

In [25]:
li.shape

(2, 6)

In [26]:
li.itemsize

4

In [37]:
li=np.array([[52,25,35,3,5,6],[66,46,3,6,36,3],[32,54,5,354,35,65],[345,35,45,3,5,34],[32,4,24,34,345,54],[33,54,35,355,535,34]])
print(li)

[[ 52  25  35   3   5   6]
 [ 66  46   3   6  36   3]
 [ 32  54   5 354  35  65]
 [345  35  45   3   5  34]
 [ 32   4  24  34 345  54]
 [ 33  54  35 355 535  34]]


In [38]:
li[1]

array([66, 46,  3,  6, 36,  3])

In [39]:
li[0]

array([52, 25, 35,  3,  5,  6])

In [40]:
li[5]

array([ 33,  54,  35, 355, 535,  34])

In [51]:
np.array([52,25,35,3,5,6],ndmin=32)

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[52,
                                      25,
                                      35,
                                       3,
                                       5,
                                       6]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [44]:
#identity matrix
c=np.eye(4)
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [57]:
c=np.eye(7,5)
print(c)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [49]:
#zeroes matrix
c=np.zeros(8)
print(c)
c

[0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
c=np.zeros((8,2))
print(c)
c

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [58]:
c=np.ones(4)
print(c)

[1. 1. 1. 1.]


In [59]:
c=np.ones((9,4))
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [62]:
c=np.ones(4,dtype="int")
print(c)

[1 1 1 1]


In [60]:
c=np.full(4,"hi")
print(c)

['hi' 'hi' 'hi' 'hi']


In [64]:
c=np.full((4,5),"hi")
print(c)
c

[['hi' 'hi' 'hi' 'hi' 'hi']
 ['hi' 'hi' 'hi' 'hi' 'hi']
 ['hi' 'hi' 'hi' 'hi' 'hi']
 ['hi' 'hi' 'hi' 'hi' 'hi']]


array([['hi', 'hi', 'hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi', 'hi', 'hi'],
       ['hi', 'hi', 'hi', 'hi', 'hi']], dtype='<U2')

In [66]:
c.fill("hey hii")
print(c)

[['he' 'he' 'he' 'he' 'he']
 ['he' 'he' 'he' 'he' 'he']
 ['he' 'he' 'he' 'he' 'he']
 ['he' 'he' 'he' 'he' 'he']]


In [67]:
c.fill(4)
print(c)

[['4' '4' '4' '4' '4']
 ['4' '4' '4' '4' '4']
 ['4' '4' '4' '4' '4']
 ['4' '4' '4' '4' '4']]


In [68]:
# using linspace:linear space
li=np.linspace(10,200,13) #190 numbers/3
print(li)

[ 10.          25.83333333  41.66666667  57.5         73.33333333
  89.16666667 105.         120.83333333 136.66666667 152.5
 168.33333333 184.16666667 200.        ]


## creating array with arange()

In [69]:
li=np.arange(25)
print(li)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [70]:
li=np.arange(25,100,2)
print(li)

[25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71
 73 75 77 79 81 83 85 87 89 91 93 95 97 99]


In [73]:
li.reshape(38,1)

array([[25],
       [27],
       [29],
       [31],
       [33],
       [35],
       [37],
       [39],
       [41],
       [43],
       [45],
       [47],
       [49],
       [51],
       [53],
       [55],
       [57],
       [59],
       [61],
       [63],
       [65],
       [67],
       [69],
       [71],
       [73],
       [75],
       [77],
       [79],
       [81],
       [83],
       [85],
       [87],
       [89],
       [91],
       [93],
       [95],
       [97],
       [99]])

## random()
- used to generate random integer
- random.randint()

In [4]:
import numpy as np

In [6]:
rn=np.random.randint(99,200)
print(rn)

122


In [8]:
# multiple random values
rn=np.random.randint(99,200,8)
print(rn)

[182 173 156 159 186 161 161 101]


In [12]:
rn=np.random.randint(99,200,8)
print(rn)
rn.reshape(8,1)
rn.reshape(2,4)

[ 99 151 104 155 102 161 105 139]


array([[ 99, 151, 104, 155],
       [102, 161, 105, 139]])

In [13]:
rn=np.random.randint(99,200,8)
print(rn)
rn.reshape(8,1)

[133 134 102 106 138 106 143 171]


array([[133],
       [134],
       [102],
       [106],
       [138],
       [106],
       [143],
       [171]])

In [10]:
rn

array([180, 177, 131, 120, 105, 173, 154, 164])

In [15]:
np.random.random((2,3))# random int b/w 0 and 1 of size(2,3)

array([[0.47764917, 0.93094625, 0.74934252],
       [0.07168743, 0.52755896, 0.07789271]])

In [16]:
np.random.rand(4,3)#sizeeeeee

array([[0.84496916, 0.8904237 , 0.75321018],
       [0.56183458, 0.84181309, 0.2952324 ],
       [0.52749853, 0.07364845, 0.09933026],
       [0.22185284, 0.00549116, 0.30976136]])

In [17]:
np.random.randn(4,3)#b/w -1 and 1

array([[ 0.88316026,  0.72487054,  0.65169093],
       [ 0.03484717,  0.71300886, -0.59783236],
       [ 0.41399059,  1.79582277,  0.47767046],
       [-1.05471407, -0.44949462,  0.95931083]])

In [25]:
np.linspace(5,15)# 75 partitions b/w 5 and 15

array([ 5.        ,  5.20408163,  5.40816327,  5.6122449 ,  5.81632653,
        6.02040816,  6.2244898 ,  6.42857143,  6.63265306,  6.83673469,
        7.04081633,  7.24489796,  7.44897959,  7.65306122,  7.85714286,
        8.06122449,  8.26530612,  8.46938776,  8.67346939,  8.87755102,
        9.08163265,  9.28571429,  9.48979592,  9.69387755,  9.89795918,
       10.10204082, 10.30612245, 10.51020408, 10.71428571, 10.91836735,
       11.12244898, 11.32653061, 11.53061224, 11.73469388, 11.93877551,
       12.14285714, 12.34693878, 12.55102041, 12.75510204, 12.95918367,
       13.16326531, 13.36734694, 13.57142857, 13.7755102 , 13.97959184,
       14.18367347, 14.3877551 , 14.59183673, 14.79591837, 15.        ])

In [24]:
np.linspace(5,15,10)

array([ 5.        ,  6.11111111,  7.22222222,  8.33333333,  9.44444444,
       10.55555556, 11.66666667, 12.77777778, 13.88888889, 15.        ])

In [21]:
11/10

1.1

# Accesing the array elements
- using index
- index of three types
- +ve indexing,-ve indexing ,fancy indexing
- -ve index: from -1 to infinite
- fancy: condition based index

In [37]:
r=np.random.randint(50,200,25).reshape(5,5)
r

array([[ 91, 128, 105,  55,  74],
       [101, 141, 190,  56,  60],
       [ 83, 199, 108, 127,  86],
       [124, 126,  96, 119, 191],
       [161, 164, 105, 124, 185]])

In [35]:
ra=np.arange(50,200,2).reshape(-3,5)
ra

array([[ 50,  52,  54,  56,  58],
       [ 60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98],
       [100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118],
       [120, 122, 124, 126, 128],
       [130, 132, 134, 136, 138],
       [140, 142, 144, 146, 148],
       [150, 152, 154, 156, 158],
       [160, 162, 164, 166, 168],
       [170, 172, 174, 176, 178],
       [180, 182, 184, 186, 188],
       [190, 192, 194, 196, 198]])

In [36]:
ra[3]

array([80, 82, 84, 86, 88])

In [38]:
ra[:]

array([[ 50,  52,  54,  56,  58],
       [ 60,  62,  64,  66,  68],
       [ 70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88],
       [ 90,  92,  94,  96,  98],
       [100, 102, 104, 106, 108],
       [110, 112, 114, 116, 118],
       [120, 122, 124, 126, 128],
       [130, 132, 134, 136, 138],
       [140, 142, 144, 146, 148],
       [150, 152, 154, 156, 158],
       [160, 162, 164, 166, 168],
       [170, 172, 174, 176, 178],
       [180, 182, 184, 186, 188],
       [190, 192, 194, 196, 198]])

In [39]:
ra[::-1]

array([[190, 192, 194, 196, 198],
       [180, 182, 184, 186, 188],
       [170, 172, 174, 176, 178],
       [160, 162, 164, 166, 168],
       [150, 152, 154, 156, 158],
       [140, 142, 144, 146, 148],
       [130, 132, 134, 136, 138],
       [120, 122, 124, 126, 128],
       [110, 112, 114, 116, 118],
       [100, 102, 104, 106, 108],
       [ 90,  92,  94,  96,  98],
       [ 80,  82,  84,  86,  88],
       [ 70,  72,  74,  76,  78],
       [ 60,  62,  64,  66,  68],
       [ 50,  52,  54,  56,  58]])

In [40]:
ra[:,1:4]

array([[ 52,  54,  56],
       [ 62,  64,  66],
       [ 72,  74,  76],
       [ 82,  84,  86],
       [ 92,  94,  96],
       [102, 104, 106],
       [112, 114, 116],
       [122, 124, 126],
       [132, 134, 136],
       [142, 144, 146],
       [152, 154, 156],
       [162, 164, 166],
       [172, 174, 176],
       [182, 184, 186],
       [192, 194, 196]])

In [41]:
ra[:4,:]

array([[50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88]])

In [44]:
for num in r[:,1:4]:
    print(num,end=" ")

[128 105  55] [141 190  56] [199 108 127] [126  96 119] [164 105 124] 

In [46]:
for num in r[:,1:4]:
    for i in num:
        if i%2==1:
            print(i)#odd numbers

105
55
141
199
127
119
105


In [47]:
ra[1:4,1:4]

array([[62, 64, 66],
       [72, 74, 76],
       [82, 84, 86]])

In [48]:
ra[1:4:2,1:4:2]

array([[62, 66],
       [82, 86]])

In [49]:
#extract the sub array containing
#alterate col in alternate rows

In [50]:
ra[-3:-1]

array([[170, 172, 174, 176, 178],
       [180, 182, 184, 186, 188]])

In [51]:
ra[::-1,::-1]

array([[198, 196, 194, 192, 190],
       [188, 186, 184, 182, 180],
       [178, 176, 174, 172, 170],
       [168, 166, 164, 162, 160],
       [158, 156, 154, 152, 150],
       [148, 146, 144, 142, 140],
       [138, 136, 134, 132, 130],
       [128, 126, 124, 122, 120],
       [118, 116, 114, 112, 110],
       [108, 106, 104, 102, 100],
       [ 98,  96,  94,  92,  90],
       [ 88,  86,  84,  82,  80],
       [ 78,  76,  74,  72,  70],
       [ 68,  66,  64,  62,  60],
       [ 58,  56,  54,  52,  50]])

In [82]:
r

array([[ 91, 128, 105,  55,  74],
       [101, 141, 190,  56,  60],
       [ 83, 199, 108, 127,  86],
       [124, 126,  96, 119, 191],
       [161, 164, 105, 124, 185]])

In [59]:
#fancy indexing 
r<100 #boolean array

array([[ True, False, False,  True,  True],
       [False, False, False,  True,  True],
       [ True, False, False, False,  True],
       [False, False,  True, False, False],
       [False, False, False, False, False]])

In [58]:
r[r<100]

array([91, 55, 74, 56, 60, 83, 86, 96])

In [62]:
#scientific computations on arrays
#perform all the operations on arrays 

In [68]:
ra=np.arange(50,100,2).reshape(5,5)
ra

array([[50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [69]:
print(r+ra)

[[141 180 159 111 132]
 [161 203 254 122 128]
 [153 271 182 203 164]
 [204 208 180 205 279]
 [251 256 199 220 283]]


In [70]:
ra.transpose()

array([[50, 60, 70, 80, 90],
       [52, 62, 72, 82, 92],
       [54, 64, 74, 84, 94],
       [56, 66, 76, 86, 96],
       [58, 68, 78, 88, 98]])

In [71]:
print(r-ra)

[[ 41  76  51  -1  16]
 [ 41  79 126 -10  -8]
 [ 13 127  34  51   8]
 [ 44  44  12  33 103]
 [ 71  72  11  28  87]]


In [72]:
print(r*ra)

[[ 4550  6656  5670  3080  4292]
 [ 6060  8742 12160  3696  4080]
 [ 5810 14328  7992  9652  6708]
 [ 9920 10332  8064 10234 16808]
 [14490 15088  9870 11904 18130]]


In [73]:
print(r/ra)

[[1.82       2.46153846 1.94444444 0.98214286 1.27586207]
 [1.68333333 2.27419355 2.96875    0.84848485 0.88235294]
 [1.18571429 2.76388889 1.45945946 1.67105263 1.1025641 ]
 [1.55       1.53658537 1.14285714 1.38372093 2.17045455]
 [1.78888889 1.7826087  1.11702128 1.29166667 1.8877551 ]]


In [74]:
print(r**ra)

[[  333882265           0  -640853583 -1299426111           0]
 [-1643396591 -1863299175           0           0           0]
 [  609870457 -1374042431           0 -1622648319           0]
 [          0           0           0 -1283839631 -1014432255]
 [ 1696640065           0  -340201231           0  2063920817]]


In [75]:
print(sum(r))

[560 758 604 481 596]


In [77]:
print(r)

[[ 91 128 105  55  74]
 [101 141 190  56  60]
 [ 83 199 108 127  86]
 [124 126  96 119 191]
 [161 164 105 124 185]]


In [78]:
print(ra)

[[50 52 54 56 58]
 [60 62 64 66 68]
 [70 72 74 76 78]
 [80 82 84 86 88]
 [90 92 94 96 98]]


In [79]:
r.dot(ra)

array([[30640, 31546, 32452, 33358, 34264],
       [36690, 37786, 38882, 39978, 41074],
       [41550, 42756, 43962, 45168, 46374],
       [47190, 48502, 49814, 51126, 52438],
       [51810, 53288, 54766, 56244, 57722]])

In [80]:
r.min()

55

In [81]:
r.max()

199

In [84]:
sum(ra[0])

270

In [85]:
ra[0]

array([50, 52, 54, 56, 58])

In [86]:
ra[0].sum()

270

In [87]:
ra[2][4]

78

In [95]:
#logarithms and exponentials

In [89]:
np.log(1)

0.0

In [90]:
np.log(10)

2.302585092994046

In [91]:
np.log2(2)

1.0

In [92]:
np.log(2)

0.6931471805599453

In [93]:
np.log(0)

<ipython-input-93-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [102]:
np.log2(4)

2.0

In [101]:
np.exp(1)

2.718281828459045

In [103]:
np.exp(np.log(1))

1.0

In [104]:
np.exp(np.log2(4))

7.38905609893065

In [105]:
np.log(np.exp(1))

1.0

In [106]:
#vectorized functions in numpy

In [107]:
def greater(a,b):
    return a if a>b else b
greater(3,4)

4

In [111]:
greater([4,5,10],[3,11,20])

[4, 5, 10]

In [126]:
a,b=[4,5,10],[3,11,20]
for i in zip(a,b):
    print(i)
type(i)

(4, 3)
(5, 11)
(10, 20)


tuple

In [128]:
a,b=[4,5,10],[3,11,20]
for i,x in zip(a,b):
    print(i,x)
type(i)
type(x)

4 3
5 11
10 20


int

In [124]:
a,b=[4,5,10],[3,11,20]
for i,x in zip(a,b):
    y=[i,x]
    print(y)
type(i)
type(x)
type(y)

[4, 3]
[5, 11]
[10, 20]


list

In [121]:
a,b=[4,5,10],[3,11,20]
n=[]
for i,x in zip(a,b):
    n.append(i) if i>x else n.append(x)
print(n)

[4, 11, 20]


In [129]:
g=np.vectorize(greater)
g(a,b)

array([ 4, 11, 20])